{% set name = "sphinxcontrib-autodoc_doxygen" %}
{% set version = "0.3.2" %}
{% set sha256 = "cc13ca218db2907c9e3cb530d21b5a7ab6c17502958b931b3e1b82b506497e1a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - sphinx >=1.5
    - docutils >=0.11
    - jinja2 >=2.3
    - lxml
    - pbr
  run:
    - python
    - sphinx >=1.5
    - docutils >=0.11
    - jinja2 >=2.3
    - lxml

test:
  requires:
    - mock
  imports:
    - sphinxcontrib.autodoc_doxygen

about:
  home: https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen
  license: MIT
  license_file: LICENSE
  summary: 'Doxygen / Sphinx bridge, with autodoc and autosummary'
  doc_url: https://rawgit.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/gh-pages/index.html
  dev_url: https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen

extra:
  recipe-maintainers:
    - rmcgibbo
