{% set name = "sphinxcontrib-autodoc_doxygen" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3af386ef57e10fbec59a5a9bf355778bd52ec98685fde956f9b01774339a5317

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - sphinx >=1.5
    - docutils >=0.11
    - jinja2 >=2.3
    - lxml
    - pbr
  run:
    - python
    - sphinx >=1.5
    - docutils >=0.11
    - jinja2 >=2.3
    - lxml

test:
  requires:
    - mock
  imports:
    - sphinxcontrib.autodoc_doxygen

about:
  home: https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen
  license: MIT
  license_file: LICENSE
  summary: 'Doxygen / Sphinx bridge, with autodoc and autosummary'
  doc_url: https://rawgit.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/gh-pages/index.html
  dev_url: https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen
